export const employees=['richard','anastasia','jean-claude','kevin','svetlana'];
export class InputError extends Error {}
export function requireManager(role){if(role!=='svetlana')throw new InputError('Only Svetlana can approve or correct transactions.');}
function required(v,n){if(typeof v!=='string'||!v.trim()||v.length>1000)throw new InputError(`${n} is required (maximum 1000 characters).`);return v.trim();}
export function money(v){const s=String(v);if(!/^\d+(\.\d{1,2})?$/.test(s)||Number(s)<=0||Number(s)>10000000)throw new InputError('Enter a positive euro amount with at most two decimals (maximum 10000000).');const [w,f='']=s.split('.');return Number(w)*100+Number(f.padEnd(2,'0'));}
export function split(v){if(!Array.isArray(v)||v.length!==3||v.some(x=>typeof x!=='number'||!Number.isFinite(x)||x<0||x>100||Math.abs(x*100-Math.round(x*100))>1e-8)||v.reduce((a,b)=>a+Math.round(b*100),0)!==10000)throw new InputError('Three commission percentages, with up to two decimals, must total 100%.');return v;}
function base(i,employee){const reference=required(i.reference,'Reference');if(!/^[A-Za-z0-9_-]{1,40}$/.test(reference))throw new InputError('Reference must contain up to 40 letters, numbers, dashes or underscores.');return {reference,employee,description:required(i.description,'Description'),amount_cents:money(i.amount)};}
export function sale(i,employee){if(!employees.slice(0,3).includes(employee))throw new InputError('Only salespeople can submit sales.');if(!['A','B'].includes(i.project))throw new InputError('Project must be A or B.');return {...base(i,employee),customer:required(i.customer,'Customer'),project:i.project,shares:split(i.shares)};}
export function allocation(v){if(!['A','B','Company overhead'].includes(v))throw new InputError('Choose A, B or Company overhead.');return v;}
export function expense(i,employee){if(employee!=='kevin')throw new InputError('Only Kevin can submit expenses.');if(!['Materials','Travel','Other'].includes(i.category))throw new InputError('Choose Materials, Travel or Other.');const proposed_allocation=allocation(i.proposed_allocation);return {...base(i,employee),category:i.category,proposed_allocation,final_allocation:proposed_allocation==='Company overhead'?proposed_allocation:null,status:proposed_allocation==='Company overhead'?'Allocated':'Awaiting allocation'};}
export function commissions(cents,shares){split(shares);const pool=Math.round(cents/10),earned=shares.map(x=>Math.round(pool*Math.round(x*100)/10000));earned[shares.indexOf(Math.max(...shares))]+=pool-earned.reduce((a,b)=>a+b,0);return {pool,earned};}
export function results(sales,expenses){const p=()=>({income:0,commissions:0,expenses:0,result:0});const t={A:p(),B:p(),company:p(),overhead:0,awaiting:0,pendingSales:0,earned:[0,0,0]};for(const s of sales){if(s.status!=='Approved'){t.pendingSales+=s.amount_cents;continue;}const c=commissions(s.amount_cents,s.approved_shares);for(const x of [t[s.project],t.company]){x.income+=s.amount_cents;x.commissions+=c.pool;}c.earned.forEach((v,i)=>t.earned[i]+=v);}for(const e of expenses){t.company.expenses+=e.amount_cents;if(!e.final_allocation)t.awaiting+=e.amount_cents;else if(e.final_allocation==='Company overhead')t.overhead+=e.amount_cents;else t[e.final_allocation].expenses+=e.amount_cents;}for(const x of [t.A,t.B,t.company])x.result=x.income-x.commissions-x.expenses;return t;}
